export const buttons = [
    {
        label: 'C',
        name: 'clear',
        background: '#D2D3DA',
        color: '#000',
    },
    {
        label: '±',
        name: '+-',
        background: '#D2D3DA',
        color: '#000',
    },
    {
        label: '%',
        name: '%',
        background: '#D2D3DA',
        color: '#000',
    },
    {
        label: '÷',
        name: '/',
        background: '#4B5EFC',
        color: '#fff',
    },
    {
        label: '7',
        name: '7',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '8',
        name: '8',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '9',
        name: '9',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '×',
        name: '*',
        background: '#4B5EFC',
        color: '#fff',
    },
    {
        label: '4',
        name: '4',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '5',
        name: '5',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '6',
        name: '6',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '-',
        name: '-',
        background: '#4B5EFC',
        color: '#fff',
    },
    {
        label: '1',
        name: '1',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '2',
        name: '2',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '3',
        name: '3',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '+',
        name: '+',
        background: '#4B5EFC',
        color: '#fff',
    },
    {
        label: '.',
        name: '.',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '0',
        name: '0',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: 'del',
        name: 'del',
        background: '#FFFFFF',
        color: '#000',
    },
    {
        label: '=',
        name: 'equal',
        background: '#4B5EFC',
        color: '#fff',
    },
]